version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: sample_db
    ports:
      - "5433:5432"
    networks:
      - pg_network

  localtunnel:
    image: node:alpine
    container_name: localtunnel_service
    working_dir: /app
    command: sh -c "npm install -g localtunnel && lt --port 5433"
    networks:
      - pg_network

networks:
  pg_network:
    driver: bridge
